"""Data-quality metrics and a shareable "data health" report.

quality_metrics : conformance, current normal form, candidate keys, and a redundancy
index (the share of redundant storage the normalization removes).
build_html_report : a self-contained HTML report (constraints, schema, metrics, top
anomalies, repair summary) renderable by a browser or Qt's QTextDocument (-> PDF).
"""
from __future__ import annotations
import html

from norma.modeling.report import _kind


def quality_metrics(table, schema, scores, threshold: float = 0.7) -> dict:
    n, d = table.n, len(table.columns)
    total = max(1, n * d)
    flagged = int((scores > threshold).sum()) if scores is not None else 0
    conformance = 1.0 - flagged / total

    rels = schema.relations_bcnf
    if rels:
        attrs = set().union(*[set(r.attributes) for r in rels])
        flat_cells = n * len(attrs)
        norm_cells = sum(len(table.df[sorted(r.attributes)].drop_duplicates()) * len(r.attributes)
                         for r in rels)
        redundancy = max(0.0, 1.0 - norm_cells / max(1, flat_cells))
    else:
        flat_cells = norm_cells = 0; redundancy = 0.0

    return {
        "rows": n, "columns": d, "flagged_cells": flagged,
        "conformance": conformance, "normal_form": schema.normal_form,
        "candidate_keys": len(schema.keys), "relations": len(rels),
        "redundancy": redundancy, "flat_cells": flat_cells, "norm_cells": norm_cells,
    }


def _e(x):
    return html.escape(str(x))


def _table(headers, rows, widths=None):
    """A QTextDocument-friendly HTML table (uses only the supported subset)."""
    out = ['<table border="1" width="100%" cellspacing="0" cellpadding="5" '
           'style="border-color:#d0d6e0;border-collapse:collapse">']
    out.append('<tr bgcolor="#eef2f8">' + "".join(
        f'<th align="left"{f" width={w}" if w else ""}>{h}</th>' for h, w in zip(headers, widths or [None] * len(headers))) + "</tr>")
    for r in rows:
        out.append("<tr>" + "".join(f'<td valign="top">{c}</td>' for c in r) + "</tr>")
    out.append("</table>")
    return "".join(out)


def _h2(title):
    return f'<br><font size="5" color="#2d7ff9"><b>{title}</b></font><hr>'


REPORT_LABELS = {
    "fr": {
        "title": "Rapport de qualité des données",
        "subtitle": "Généré par norma (découverte non supervisée de contraintes).",
        "rows": "lignes", "columns": "colonnes", "cells": "cellules",
        "indicators": "Indicateurs", "conformance": "Conformance", "normal_form": "Forme normale",
        "candidate_keys": "Clés candidates", "redundancy": "Redondance éliminée",
        "flagged": "Cellules signalées",
        "constraints": "Contraintes découvertes", "type": "Type", "rule": "Règle", "confidence": "Confiance",
        "schema": "Schéma relationnel proposé (BCNF)", "relation": "Relation", "attributes": "Attributs", "key": "Clé",
        "repair": "Réparation proposée", "row": "Ligne", "column": "Colonne", "before": "Avant", "after": "Après",
        "anomalies": "Cellules les plus anormales", "value": "Valeur", "score": "Score",
    },
    "en": {
        "title": "Data quality report",
        "subtitle": "Generated by norma (unsupervised constraint discovery).",
        "rows": "rows", "columns": "columns", "cells": "cells",
        "indicators": "Indicators", "conformance": "Conformance", "normal_form": "Normal form",
        "candidate_keys": "Candidate keys", "redundancy": "Redundancy removed",
        "flagged": "Flagged cells",
        "constraints": "Discovered constraints", "type": "Type", "rule": "Rule", "confidence": "Confidence",
        "schema": "Proposed relational schema (BCNF)", "relation": "Relation", "attributes": "Attributes", "key": "Key",
        "repair": "Proposed repair", "row": "Row", "column": "Column", "before": "Before", "after": "After",
        "anomalies": "Most anomalous cells", "value": "Value", "score": "Score",
    },
}


def build_html_report(table, rules, schema, metrics, anomalies=None, repair=None, lang="fr") -> str:
    """Self-contained report using only QTextDocument-supported HTML (table layout, font
    tags, bgcolor) so it renders identically in the app and in the exported PDF. `lang`
    selects the report language ('fr' / 'en'); French uses proper accents."""
    m = metrics
    L = REPORT_LABELS.get(lang, REPORT_LABELS["fr"])
    P = ['<html><body style="font-family:Helvetica,Arial,sans-serif;color:#1a1f29">']
    P.append(f'<font size="6"><b>{_e(L["title"])}</b></font><br>')
    P.append(f'<font size="4" color="#445">{_e(table.name)} &nbsp;&middot;&nbsp; '
             f'{m["rows"]} {_e(L["rows"])} &times; {m["columns"]} {_e(L["columns"])}</font><br>')
    P.append(f'<font color="#778">{_e(L["subtitle"])}</font>')

    cards = [(L["conformance"], f"{m['conformance']*100:.1f}%"),
             (L["normal_form"], m["normal_form"]),
             (L["candidate_keys"], str(m["candidate_keys"])),
             (L["redundancy"], f"{m['redundancy']*100:.0f}%"),
             (L["flagged"], str(m["flagged_cells"]))]
    P.append(_h2(_e(L["indicators"])))
    P.append('<table width="100%" cellspacing="6" cellpadding="10"><tr>')
    for label, val in cards:
        P.append(f'<td align="center" bgcolor="#f3f7ff" width="20%">'
                 f'<font size="6" color="#2d7ff9"><b>{_e(val)}</b></font><br>'
                 f'<font size="2" color="#667">{_e(label)}</font></td>')
    P.append("</tr></table>")

    P.append(_h2(f'{_e(L["constraints"])} ({len(rules)})'))
    P.append(_table([L["type"], L["rule"], L["confidence"]],
                    [[_e(_kind(o)), _e(o), f"{getattr(o, 'confidence', 1.0):.3f}"] for o in rules],
                    widths=["18%", None, "14%"]))

    P.append(_h2(_e(L["schema"])))
    P.append(_table([L["relation"], L["attributes"], L["key"]],
                    [[_e(r.name), _e(", ".join(sorted(r.attributes))), _e(", ".join(sorted(r.key)))]
                     for r in schema.relations_bcnf], widths=["14%", None, "26%"]))

    if repair is not None and repair.n_edits:
        P.append(_h2(f'{_e(L["repair"])} ({repair.n_edits} {_e(L["cells"])})'))
        P.append(_table([L["row"], L["column"], L["before"], L["after"], L["rule"]],
                        [[str(e.row), _e(e.column), _e(e.old), f'<font color="#1b8a5a">{_e(e.new)}</font>', _e(e.rule)]
                         for e in repair.edits[:15]], widths=["8%", "16%", "16%", "16%", None]))

    if anomalies:
        P.append(_h2(_e(L["anomalies"])))
        P.append(_table([L["row"], L["column"], L["value"], L["score"]],
                        [[str(a["row"]), _e(a["column"]), _e(a["value"]), f"{a['score']:.3f}"]
                         for a in anomalies[:15]], widths=["10%", "26%", None, "14%"]))

    P.append("</body></html>")
    return "\n".join(P)
