"""Bidirectional bridge between the relational schema and SQL DDL.

  schema_to_ddl(session)  : normalized relations -> CREATE TABLE ... PRIMARY KEY,
                            plus CHECK / ASSERTION / quality-rule stubs for the
                            constraints that are not expressible as table structure.
  parse_ddl(text)         : CREATE TABLE statements -> [(name, attributes, key)],
                            so a schema edited in SQL can be shown back visually.
"""
from __future__ import annotations
import re

from norma.core.table import NUMERIC
from norma.core.constraint import FunctionalDependency, DenialConstraint, LinearConstraint


def _sql_type(session, col: str) -> str:
    if session.table is not None and session.table.kinds.get(col) == NUMERIC:
        return "DOUBLE PRECISION"
    return "VARCHAR(255)"


def schema_to_ddl(session, which: str = "bcnf") -> str:
    sch = session.schema
    rels = sch.relations_bcnf if which == "bcnf" else sch.relations_3nf
    out = [f"-- Normalized relational schema ({which.upper()}) generated by norma",
           f"-- Forme normale de la table plate : {sch.normal_form}", ""]
    for r in rels:
        cols = sorted(r.attributes)
        lines = [f"    {c:<22} {_sql_type(session, c)}" for c in cols]
        body = ",\n".join(lines)
        pk = ", ".join(sorted(r.key))
        ddl = f"CREATE TABLE {r.name} (\n{body},\n    PRIMARY KEY ({pk})\n);"
        out.append(ddl); out.append("")

    extra = _nonstructural(session)
    if extra:
        out.append("-- Contraintes non structurelles (a imposer en SQL) :")
        out.extend(extra)
    return "\n".join(out)


def _nonstructural(session) -> list[str]:
    lines = []
    for r in session.rules:
        if not r.enabled:
            continue
        o = r.obj
        if isinstance(o, LinearConstraint):
            terms = " ".join(f"{'+' if c >= 0 else '-'} {abs(c):g}*{col}" for col, c in o.coefficients)
            lines.append(f"-- linear:  CHECK ( ABS( {terms.lstrip('+ ')} - {o.offset:g} ) <= {max(o.tolerance, 1e-6):g} )")
        elif isinstance(o, DenialConstraint):
            preds = " AND ".join(f"a.{p.left} {p.op} b.{p.right}" for p in o.predicates)
            lines.append(f"-- order:   CREATE ASSERTION CHECK ( NOT EXISTS ("
                         f" SELECT 1 FROM T a, T b WHERE {preds} ) )")
        elif isinstance(o, FunctionalDependency) and o.confidence < 0.999:
            lhs = ", ".join(o.lhs)
            lines.append(f"-- approx FD ({o.confidence:.2f}):  rule {lhs} -> {o.rhs}  "
                         f"(quality check, not enforced as a key)")
    return lines


_CREATE = re.compile(r"CREATE\s+TABLE\s+(\w+)\s*\((.*?)\);", re.IGNORECASE | re.DOTALL)
_PK = re.compile(r"PRIMARY\s+KEY\s*\(([^)]*)\)", re.IGNORECASE)


def parse_ddl(text: str):
    """Return [(name, [attributes], [key])] parsed from CREATE TABLE statements."""
    relations = []
    for m in _CREATE.finditer(text):
        name, body = m.group(1), m.group(2)
        key = []
        attrs = []
        for raw in body.split(","):
            part = raw.strip()
            if not part or part.startswith("--"):
                continue
            pk = _PK.search(part)
            if pk:
                key = [a.strip() for a in pk.group(1).split(",") if a.strip()]
                continue
            if part.upper().startswith(("PRIMARY", "FOREIGN", "CONSTRAINT", "CHECK", "UNIQUE")):
                continue
            attrs.append(part.split()[0])
        relations.append((name, attrs, key or attrs[:1]))
    return relations
